import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import WagmiProvider from "./wagmiProvider";
import SessionProvider from "./sessionProvider";
import { lilita_one, nunito, concert } from "@/ui/Fonts";
import Background from "@/components/Background";
import ChatAI from "@/components/ChatAI";

export const metadata: Metadata = {
  title: "RunBro",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lilita_one.variable} ${nunito.className} ${concert.variable}`}
      >
        <WagmiProvider>
          <SessionProvider>
            <main className="min-h-screen w-full flex flex-col bg-transparent text-white relative z-10">
              <Header />
              {children}
              <ChatAI />
            </main>
            <Background />
          </SessionProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
