import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import WagmiProvider from "./wagmiProvider";
import SessionProvider from "./sessionProvider";

export const metadata: Metadata = {
  title: "RunBro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WagmiProvider>
          <SessionProvider>
            <main className="min-h-screen w-full flex flex-col px-[5vh]">
              <Header />
              {children}
            </main>
          </SessionProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
